### ISSUE TITLE
Add activation information to readme

### ISSUE THREAD

**Issue by calebmeyer** [nashamri/spacemacs-theme#15]
I'm brand new to emacs, and I think your theme looks awesome! I ran the install instructions, but that didn't change my syntax highlighting. Can you add instructions for both trying out and permanently setting these themes? If it makes a difference, can you also add instructions for spacemacs?

**Comment by nashamri** [comment]
Thanks @calebmeyer :smile: 
I'll try to add more info to how to install the theme. But if you followed the instructions already there, it should work. Not having syntax highlighting could be because you didn't activate a major mode for the file you are editing. For example, if you are editing an elisp file, you need to activate the `emacs-lisp-mode` by `M-x emacs-lisp-mode` to get syntax highlighting and other goodies.

**Comment by calebmeyer** [comment]
Thanks for getting back to me! I eventually figured out that I just needed to move the theme to the top of the list in my `~/.spacemacs` to activate it.

**Comment by nashamri** [comment]
oh that's good. I'm sorry for being late, I was really busy for the last two weeks or so.
Closing this issue for now :smile:
