### ISSUE TITLE
I can't use your theme as an extension anymore ...

### ISSUE THREAD

**Issue by ahmadseleem** [nashamri/spacemacs-theme#16]
I think it was the last update of spacemacs who broke it...
does anyone have the same problem ?

**Comment by nashamri** [comment]
Hey @ahmadseleem I was away for couple of weeks and I'm not on top of things. I know that spacemacs changed something about the way it works with packages. I read it in their gitter channel some days ago. It might be intentional not to use "extensions" any more and stick to packages only, but I need to investigate it a bit more.

**Comment by nashamri** [comment]
@ahmadseleem this is a quote of the message from sylvian regarding the extension:
"@/all I pushed to develop the long awaited new package lists, the spacemacs layer has been updated accordingly so `extensions.el` does not exist anymore for this layer, `packages.el` now contains everything."

So I guess it's intentional :smile:

**Comment by nashamri** [comment]
I'm wondering why you want to use it as an extension, though?
If you are on `develop` the theme is already part of the core packages of spacemacs and it pulls the latest updates from MELPA.

**Comment by ahmadseleem** [comment]
got you! but, I'm not  on develop. how do I switch to develop. I just use emacs for some languages but, mainly using Atom with vim-mode. that's why I had no time to read everything about spacemacs. I just wanted to get the job done as I use to use Emacs:
https://github.com/ahmadseleem/ViMacs

I used to collect these configs last year before Spacemacs  got popular. but, then I forward people to use spacemacs. because, I didn't know much about elisp; I just liked that idea of using vim keybindings.

I wish you can port the theme I used to used with ViMacs it's called mac-classic-theme:
you can find it in the repo above...
It's the best light theme IMO.

**Comment by ahmadseleem** [comment]
here's the link:
https://github.com/ahmadseleem/ViMacs/tree/master/elpa/color-theme/themes

**Comment by ahmadseleem** [comment]
It works now as a package. cool! thanks!

What do you think about making line-numbers light gray and it's background as the main back ground ?

**Comment by ahmadseleem** [comment]
also, I do like the new very green bg of comments :+1:

**Comment by ahmadseleem** [comment]
like that for example:
;;;;; linum-mode
     `(linum ((,class (:foreground "#ACAEAE" :background ,bg1))))

**Comment by nashamri** [comment]
Hey @ahmadseleem, to check `develop` of spacemacs, all you need to do is go to your `.emacs.d` dir and checkout the `develop` branch.

As for the line-numbers, I remeber we had a discussion about it in spacemacs gitter room and this commit was the result of that discussion https://github.com/nashamri/spacemacs-theme/commit/003e1d60d9b2086c4bbbf0f5dab47df0a5c36928

So I don't want to change it again :smile: sorry about that, you can always override these settings to your liking by adding your modification to your `.spacemacs` file.

**Comment by ahmadseleem** [comment]
Cool! thanks Nasser!

**Comment by nashamri** [comment]
You are welcome ahmad, I'm going to close this issue now :smile:
