### ISSUE TITLE
improve color in avy (GUI)

### ISSUE THREAD

**Issue by casouri** [nashamri/spacemacs-theme#99]
I've seen an similar issue for terminal. In GUI, it is even harder to see.

<img width="1158" alt="screen shot 2017-12-30 at 5 36 26 pm" src="https://user-images.githubusercontent.com/13118647/34457738-705ae572-ed88-11e7-9249-d1447f549d61.png">

Maybe it can be changed to some brighter colors?

**Comment by nashamri** [comment]
Hey @casouri just fixed this as shown in the screenshot. I'll push the update now.
![archlabs_2018-01-07-24_1920x1080](https://user-images.githubusercontent.com/1207107/34650240-c65857f6-f3ce-11e7-8fb3-933b538aaf31.png)

**Comment by petrucci4prez** [comment]
Would like to reopen this issue because I think there is a better solution. In org mode, the third level headlines are nearly the same color as the yellow-green avy highlight, so it is a pain to read here and in whatever other modes the yellow-green text appears:
![image](https://user-images.githubusercontent.com/6629118/35716514-63b3b36a-07a7-11e8-819f-151b7a53e04a.png)

Many other themes seem to highlight the background instead of changing the foreground. I like the colors; would it be possible to highlight the background using the same colors to make the text "pop out" more?

**Comment by casouri** [comment]
@petrucci4prez If you enable `avy-background` such as `(setq avy-background t)`.
Any candidates looks clear even in org mode.

<img width="689" alt="screen shot 2018-02-16 at 9 31 01 am" src="https://user-images.githubusercontent.com/13118647/36312382-4c7a1292-12fc-11e8-96d3-86c637043b94.png">

**Comment by casouri** [comment]
I don't think it's a problem so I'll close this.
